app:
  name: wallet-tracker-backend

server:
  host: localhost
  port: 1323

database:
  db_host:
  db_port:
  db_name:
  db_username:
  db_password:
  db_postgres_ssl_mode:

jwt:
  issuer:
  expired:
  secret:
  refresh_expired:
  refresh_secret: